[workspace]
members = ["walkers", "demo", "demo_native", "demo_web"]

[workspace.package]
version = "0.10.1"

[workspace.dependencies]
image = "*"
log = "0.4"
egui = "0.23"
egui_extras = { version = "0.23", features = ["image"] }
eframe = "0.23"
