[workspace]
members = ["walkers", "demo", "demo_native", "demo_web", "demo_android"]
resolver = "2"

[workspace.package]
version = "0.14.0"

[workspace.dependencies]
image = "0.24"
log = "0.4"
egui = "0.24"
egui_extras = { version = "0.24", features = ["svg"] }
eframe = {version =  "0.24", features = ["android-game-activity"] }
