[workspace]
members = [
    "walkers",
    "demo",
    "demo_native",
    "demo_web",
    "demo_android/rust",
    "hypermocker",
]
resolver = "2"

[workspace.package]
version = "0.18.0"

[workspace.dependencies]
image = "0.24"
log = "0.4"
egui = "0.26"
egui_extras = { version = "0.26", features = ["svg"] }
eframe = "0.26"
egui-winit = "0.26"
