[package]
name = "demo_web"
version.workspace = true
edition = "2021"
publish = false

[dependencies]
demo = { path = "../demo" }
eframe = "0.23"
egui = "0.23"
log = "0.4"
wasm-bindgen-futures = "0.4"
