[package]
name = "demo_native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
demo = { path = "../demo" }
eframe = "0.22"
egui = "0.22"
env_logger = "0.10"
