name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust Stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        target: wasm32-unknown-unknown

    - name: Build
      run: cargo build --verbose

    - name: Install Trunk
      run: cargo install trunk

    - name: Build Demo Web
      run: env -C demo_web trunk build

    - name: Build Demo Native
      run: env -C demo_native cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Check rust formatting
      run:  cargo fmt --all --check

    - name: Clippy
      run:  cargo clippy --all-features -- -D warnings 

    - name: Documentation
      run:  cargo doc
